version: "3.8"

services:
  web:
    image: placement23
    container_name: placement23
    restart: always
    build:
        context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - placement23uploads:/code/uploads
    ports:
      - "10010:5000"
    command: node app.js
    env_file:
      - backend/.env.production
      - frontend/.env.production

volumes:
    placement23uploads: